local configs = require("nvim-treesitter.configs")

configs.setup({
    ensure_installed = {
        "arduino",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "csv",
        "dart",
        "dockerfile",
        "editorconfig",
        "elixir",
        "erlang",
        "fsharp",
        "git_config",
        "gitignore",
        "gpg",
        "haskell",
        "helm",
        "html",
        "java",
        "javascript",
        "json",
        "kotlin",
        "latex",
        "lua",
        "make",
        "markdown",
        "nginx",
        "powershell",
        "proto",
        "python",
        "rust",
        "scss",
        "solidity",
        "sql",
        "ssh_config",
        "svelte",
        "terraform",
        "typescript",
        "vim",
        "vimdoc",
    },
    sync_install = false,
    highlight = {
        enable = true,
    },
    indent = {
        enable = true,
    },
})
