return {
    {
        "rcarriga/nvim-dap-ui",
        dependencies = {
            {
                "mfussenegger/nvim-dap",
                keys = {
                    {
                        "<leader>b",
                        function()
                            require("dap").toggle_breakpoint()
                        end,
                    },
                    {
                        "<F5>",
                        function()
                            require("dap").continue()
                        end,
                    },
                    {
                        "<F10>",
                        function()
                            require("dap").step_over()
                        end,
                    },
                    {
                        "<F11>",
                        function()
                            require("dap").step_into()
                        end,
                    },
                    {
                        "<F12>",
                        function()
                            require("dap").step_out()
                        end,
                    },
                },
            },
            "nvim-neotest/nvim-nio",
        },
    },
}
